# Workflow to publish the Mozilla extension
# Conditionally publishes the current branch to GitHub Pages, and/or
# updates docker image for moz-extension.kiwix.org
# This workflow uses openzim/docker-publish-action@v6
# Documentation: https://github.com/openzim/docker-publish-action#readme

name: Publish Mozilla extension

# Controls when the action will run.
on:
  # Triggers the workflow on push to master
  push:
    branches: [ master ]
  # Triggers the workflow when a release is published
  release:
    types: [ published ]

  # DEV: You can call this dispatch for testing from the REST API and set input values with
  # "inputs": {
  #    "version": "{tag}"
  # }
  # API: 'https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches'
  # Documentation of API: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
  workflow_dispatch:
    inputs:
      version:
        description: Set any override version number to use (overrides on-master and tag-pattern). If it matches ^[0-9.]+, it will set the appVersion and will be visible to users. Non-matching values will cause appVersion to be used.
        required: true
        default: 'dev'
      target:
        description: 'Set the target to update: "ghpages" or "docker" (will update GitHub Pages by default)'
        required: false
        default: ghpages

jobs:
  build-and-push:
    name: Deploy Mozilla extension
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Modify version in source files
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          TAG_VERSION: ${{ github.event.release.tag_name }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          chmod +x ./scripts/rewrite_app_version_number.sh
          ./scripts/rewrite_app_version_number.sh
      # Publish to docker only if explicitly requested or we are releasing
      - name: Build and push to docker
        if: github.event.inputs.target == 'docker' || github.event_name == 'release'
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/kiwix-moz-extension
          credentials: |
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
          tag-pattern: /^v*([0-9.]+)$/
          latest-on-tag: true
          dockerfile: docker/dockerfile-moz-extension.pwa
          restrict-to: kiwix/kiwix-js
          registries: docker.io
          manual-tag: ${{ github.event.inputs.version }}
      # Publish to GitHub Pages if explicitly requested, or if releasing, or if pushing to master
      - name: Publish to GitHub Pages
        if: github.event.inputs.target == 'ghpages' || github.event_name == 'release' || github.event_name == 'push'
        run: |
          # Set up username and email
          echo "Publishing to GitHub pages..."
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          if [ ! -z "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Set GitHub Pages release version"
          fi
          # Set gh-pages branch on origin to the currently checked-out branch
          git push origin HEAD:gh-pages --force
